// Content for the static marketing site. Keep claims accurate to the product.
// Healthcare verticals (dental, medical, therapy, physio, medspa) are intentionally
// excluded until SlotRecover is HIPAA/GDPR-special-category ready.

export const SITE_URL = 'https://www.slotrecover.pro'
export const PRODUCT = 'SlotRecover'
export const COMPANY = 'Dhali Services'

// Fixed regional price points (monthly). Placeholders until pricing is final.
export const PRICES = {
  USD: { amount: 29, symbol: '$', label: 'USD' },
  EUR: { amount: 27, symbol: '€', label: 'EUR' },
  GBP: { amount: 24, symbol: '£', label: 'GBP' },
}
export const TRIAL_DAYS = 7

export const FEATURES = [
  ['Automatic confirmations', 'Every booked client gets one confirmation email in the 24 hours before their appointment, with Confirm, Reschedule and Cancel buttons.'],
  ['Waitlist that fills itself', 'When someone cancels or reschedules, the slot is offered to the best-matching client on your waitlist. If they pass, it moves to the next person automatically.'],
  ['WhatsApp reminders in one tap', 'Open a ready-written WhatsApp message with confirm, reschedule and cancel links for any client who hasn’t replied.'],
  ['Staff-aware availability', 'Add your team and the services each person offers. A time stays bookable while anyone qualified is free, and clients can choose who they see.'],
  ['Recovered revenue you can see', 'Your dashboard shows revenue at risk from cancellations and the revenue SlotRecover won back from your waitlist.'],
  ['Works on every phone', 'Install SlotRecover on Android or iPhone like an app and get a notification when confirmations go out.'],
]

export const STEPS = [
  ['Book', 'Add the appointment in seconds. SlotRecover shows only free times based on your hours and staff.'],
  ['Confirm', 'Your client gets a confirmation request before the visit and can confirm, reschedule or cancel in one tap.'],
  ['Recover', 'A cancelled or moved slot is offered to your waitlist straight away, with a 15-minute window per client.'],
  ['Report', 'Filled slots count as recovered revenue, so you can see exactly what the waitlist earned you.'],
]

export const HOME_FAQ = [
  ['What is SlotRecover?', 'SlotRecover is appointment software for small service businesses that reduces empty slots. It asks clients to confirm, catches cancellations early, and automatically offers freed-up times to people on your waitlist.'],
  ['How is this different from a booking app?', 'Most booking apps stop at taking the booking. SlotRecover focuses on what happens after: confirming attendance, handling reschedules, and refilling cancelled slots from a waitlist so the time still earns money.'],
  ['Do my clients need to download anything?', 'No. Clients use links in their email or WhatsApp message. Only you and your team use the SlotRecover app.'],
  ['Can I use it with more than one staff member?', 'Yes. Add your staff and the services each person offers. Availability, waitlist offers and reminders all respect who is free.'],
  ['How much does it cost?', `There is a ${TRIAL_DAYS}-day free trial, then a single monthly plan priced in your local currency. You can cancel any time from Settings.`],
  ['Is my data safe and GDPR-ready?', 'Each business’s data is isolated with row-level security and encrypted in transit and at rest. We act as your processor under a Data Processing Addendum with EU Standard Contractual Clauses.'],
]

export const PRICING_FAQ = [
  ['Why do I see prices in my currency?', 'We show prices in US dollars, euros or British pounds based on your location. Everywhere else, including India, sees US dollars. You can switch currency on this page.'],
  ['Is tax included?', 'Prices exclude VAT, GST or sales tax, which is added where it applies.'],
  ['What happens after the free trial?', `Your plan starts automatically when the ${TRIAL_DAYS}-day trial ends. Cancel before then from Settings and you won’t be charged.`],
  ['Can I cancel any time?', 'Yes. Cancel in Settings → Subscription. You keep access until the end of the period you’ve paid for.'],
  ['Do you charge per staff member?', 'Not at the moment. One plan covers your business and your team.'],
]

// Industry landing pages. Example figures are illustrative.
export const INDUSTRIES = [
  {
    slug: 'hair-salons', name: 'Hair salons', short: 'Hair salons & stylists',
    title: 'No-Show & Cancellation Software for Hair Salons | SlotRecover',
    h1: 'Fill last-minute cancellations at your hair salon',
    desc: 'Confirm salon appointments automatically and refill cancelled color, cut and styling slots from your waitlist. Built for independent stylists and salons.',
    intro: 'A cancelled color appointment can leave two or three hours of chair time empty. SlotRecover confirms every booking in advance and, when a client cancels, offers the slot to someone on your waitlist who wants that exact service.',
    leaks: ['Long color and balayage services leave big gaps when they cancel late', 'Clients forget, then text “running late” or don’t show at all', 'Stylists lose income on days with two or three gaps'],
    helps: ['Confirmation requests go out the day before, so you know who is coming', 'Cancelled slots are offered to waitlisted clients for the same service', 'Clients can pick their stylist when they reschedule'],
    example: 'Example: a 2-hour color appointment at $180 cancels at 9 AM. SlotRecover offers it to the first matching waitlisted client, who takes it within 15 minutes. The slot is filled and $180 shows as recovered revenue.',
    appointments: ['Cut & style', 'Color', 'Balayage', 'Root touch-up', 'Blow-dry', 'Extensions consultation'],
    faqs: [['Does it work for booth renters and independent stylists?', 'Yes. You can use it on your own, or add staff if you run a salon team.'], ['Can I offer a slot only to clients who want the same service?', 'Yes. Waitlist matching uses the service, the time window the client can make, and how much notice they need.'], ['Can I add a late-cancellation policy?', 'Yes. Add a note in Settings, such as your cancellation fee policy. It is included in confirmation emails and WhatsApp reminders.']],
  },
  {
    slug: 'barbershops', name: 'Barbershops', short: 'Barbershops',
    title: 'Barbershop Appointment Reminders & Waitlist | SlotRecover',
    h1: 'Keep every barber’s chair busy',
    desc: 'Automatic confirmations and a self-filling waitlist for barbershops. Reduce no-shows and refill cancelled cuts with clients who want the next free slot.',
    intro: 'Short appointments add up fast, and every no-show is a chair you can’t bill. SlotRecover confirms bookings in advance and pushes freed-up times to waitlisted clients.',
    leaks: ['Short 30-minute cuts make no-shows easy for clients to shrug off', 'Walk-in demand doesn’t always match the empty slots', 'Several barbers means gaps are hard to track'],
    helps: ['Clients confirm, reschedule or cancel from one message', 'Freed slots go to waitlisted clients who want that time and barber', 'Availability respects which barbers are free'],
    example: 'Example: a $35 fade at 5:30 PM cancels at 3 PM. A waitlisted client who wanted an evening slot takes it from the offer email.',
    appointments: ['Haircut', 'Fade', 'Beard trim', 'Hot towel shave', 'Kids cut'],
    faqs: [['Can clients choose their barber?', 'Yes. When clients reschedule they can pick “Any available” or a specific barber.'], ['Do clients need an app?', 'No. They use links in email or WhatsApp.'], ['Can I see who hasn’t confirmed?', 'Yes. The Messaging page lists everyone awaiting a reply, with a one-tap WhatsApp nudge.']],
  },
  {
    slug: 'nail-salons', name: 'Nail salons', short: 'Nail salons & nail techs',
    title: 'Nail Salon No-Show Software & Waitlist | SlotRecover',
    h1: 'Turn nail salon cancellations into filled appointments',
    desc: 'Confirm manicure and pedicure bookings automatically and refill cancellations from your waitlist. For nail salons and independent nail technicians.',
    intro: 'Gel sets and full sets are booked days ahead, and a late cancellation is hard to fill by hand. SlotRecover asks clients to confirm and automatically offers any freed time to your waitlist.',
    leaks: ['Clients book several days out and forget', 'Hand-texting waitlisted clients takes time you don’t have between sets', 'Every tech on the team has their own gaps'],
    helps: ['One confirmation message the day before each appointment', 'Automatic offers to waitlisted clients with a 15-minute window each', 'Staff-aware availability across your team'],
    example: 'Example: a $65 gel full set is cancelled the morning of. The next matching waitlisted client accepts, and the slot is filled without a single manual text.',
    appointments: ['Gel manicure', 'Acrylic full set', 'Infill', 'Pedicure', 'Nail art'],
    faqs: [['Does it work for a solo nail tech?', 'Yes. SlotRecover works for one person or a full salon team.'], ['Can I send reminders on WhatsApp?', 'Yes. Tap the WhatsApp button next to any upcoming appointment to open a ready-written message.'], ['Can I set my working hours?', 'Yes. Set working days, opening hours and slot spacing in Settings.']],
  },
  {
    slug: 'lash-and-brow-studios', name: 'Lash & brow studios', short: 'Lash, brow & beauty studios',
    title: 'Lash & Brow Studio Appointment Software | SlotRecover',
    h1: 'Stop losing lash refills to no-shows',
    desc: 'Automatic confirmation requests and waitlist refills for lash technicians, brow studios and beauty artists.',
    intro: 'Lash refills run on tight schedules. When one client cancels, the slot is perfect for someone who is overdue. SlotRecover finds them for you.',
    leaks: ['Refill clients cancel when their lashes still look fine', 'Gaps between long full sets are hard to fill', 'Chasing confirmations by text eats your breaks'],
    helps: ['Clients confirm in one tap', 'Cancelled times are offered to waitlisted clients for the same treatment', 'Your cancellation policy is included in every reminder'],
    example: 'Example: a $95 lash refill cancels 3 hours before. A waitlisted client who wanted an earlier date takes the slot.',
    appointments: ['Lash refill', 'Classic full set', 'Volume set', 'Brow lamination', 'Brow shape & tint', 'Waxing'],
    faqs: [['Can clients join a waitlist themselves?', 'Yes. If no time works when rescheduling, clients can join the waitlist for that date.'], ['Can I add my patch test or deposit policy?', 'Yes. Add it as your note to clients in Settings.'], ['Is there a free trial?', `Yes, ${TRIAL_DAYS} days.`]],
  },
  {
    slug: 'spas-and-estheticians', name: 'Spas & estheticians', short: 'Day spas & estheticians',
    title: 'Spa & Esthetician Booking Confirmations and Waitlist | SlotRecover',
    h1: 'Refill empty treatment rooms at your spa',
    desc: 'Reduce no-shows for facials, body treatments and spa services with automatic confirmations and a waitlist that fills cancellations for you.',
    intro: 'An empty treatment room still costs you staff time and rent. SlotRecover confirms spa bookings in advance and fills cancellations from your waitlist, matched by treatment and therapist.',
    leaks: ['Long treatments leave expensive gaps', 'Gift-voucher clients book and forget', 'Matching the right therapist to a freed slot is manual'],
    helps: ['Confirmation requests before every visit', 'Waitlist offers that respect the service and the therapist', 'Recovered revenue tracked on your dashboard'],
    example: 'Example: a 90-minute $150 facial cancels the evening before. The first matching waitlisted client books it from the offer email.',
    appointments: ['Facial', 'Body treatment', 'Peel', 'Hydrafacial', 'Waxing', 'Spa package'],
    faqs: [['Can I assign services to specific therapists?', 'Yes. In Settings → Staff, tick the services each person offers.'], ['Does it work on my phone?', 'Yes. Install SlotRecover on Android or iPhone from your browser.'], ['Can I use it alongside my current booking tool?', 'SlotRecover works on its own: add appointments in SlotRecover and it handles confirmations and refills. It doesn’t sync with other booking tools yet.']],
  },
  {
    slug: 'massage-therapists', name: 'Massage therapists', short: 'Massage therapists',
    title: 'Massage Therapist No-Show Software | SlotRecover',
    h1: 'Fill cancelled massage sessions automatically',
    desc: 'Automatic confirmations and a waitlist that refills cancelled 30, 60 and 90-minute massage sessions. For independent therapists and massage studios.',
    intro: 'When a 60-minute session cancels, that hour is gone unless someone else can take it. SlotRecover offers it to waitlisted clients the moment it opens up.',
    leaks: ['Clients cancel when they feel better or get busy', 'You can’t text a waitlist while you’re with a client', 'Evening and weekend slots are in demand but go unfilled after cancellations'],
    helps: ['Confirmation requests go out automatically', 'Freed sessions are offered while you keep working', 'Session length sets exactly how long each slot blocks your day'],
    example: 'Example: a $110 deep-tissue session cancels at noon. A waitlisted client who asked for any evening that week takes it.',
    appointments: ['30-minute massage', '60-minute massage', '90-minute massage', 'Sports massage', 'Prenatal massage'],
    faqs: [['Can I set different lengths per service?', 'Yes. Each service has its own length and price.'], ['How long does a waitlist client have to accept?', 'Each offer lasts 15 minutes, then moves to the next matching client.'], ['Can I use it as a mobile therapist?', 'Yes. SlotRecover works for studio and mobile therapists.']],
  },
  {
    slug: 'tattoo-studios', name: 'Tattoo studios', short: 'Tattoo & piercing studios',
    title: 'Tattoo Studio Booking Confirmations & Waitlist | SlotRecover',
    h1: 'Don’t let a cancelled tattoo session cost you the day',
    desc: 'Confirm tattoo and piercing appointments automatically and offer cancelled sessions to your waitlist. Built for artists and studios.',
    intro: 'Tattoo sessions are long and booked weeks ahead. A last-minute cancellation can wipe out a whole day. SlotRecover confirms clients in advance and offers freed sessions to your waitlist.',
    leaks: ['Multi-hour sessions leave huge gaps', 'Flash and short-notice clients never hear about openings', 'Artists each manage their own calendar'],
    helps: ['Confirmation requests before every session', 'Automatic offers to waitlisted clients for that artist', 'Your deposit policy included in reminders'],
    example: 'Example: a 3-hour session cancels the day before. A waitlisted client who wanted that artist takes the slot from the offer email.',
    appointments: ['Tattoo session', 'Consultation', 'Touch-up', 'Piercing', 'Flash day slot'],
    faqs: [['Can clients choose a specific artist?', 'Yes. Clients can pick an artist when they reschedule, and waitlist entries can be tied to an artist.'], ['Can I include my deposit policy?', 'Yes. Add it as your note to clients in Settings.'], ['Does it take deposits?', 'Deposits aren’t collected yet. Your policy text is shown in every reminder.']],
  },
  {
    slug: 'personal-trainers', name: 'Personal trainers', short: 'Personal trainers & Pilates',
    title: 'Personal Trainer & Pilates Session Reminders | SlotRecover',
    h1: 'Fewer missed sessions for personal trainers and Pilates studios',
    desc: 'Automatic session confirmations and a waitlist that refills cancelled 1:1 training, Pilates and yoga sessions.',
    intro: 'Early-morning and evening sessions are the first to be cancelled and the hardest to refill. SlotRecover confirms sessions ahead of time and offers freed slots to clients who want them.',
    leaks: ['Clients skip sessions when motivation dips', 'Prime-time slots sit empty after late cancellations', 'You end up texting clients one by one'],
    helps: ['Confirmation requests before every session', 'Waitlist offers for prime-time slots', 'One-tap WhatsApp reminders for anyone who hasn’t confirmed'],
    example: 'Example: a $70 6 PM session cancels at lunchtime. A waitlisted client who wanted an evening slot takes it.',
    appointments: ['1:1 training', 'Assessment', 'Private Pilates', 'Reformer session', 'Private yoga'],
    faqs: [['Does it work for group classes?', 'SlotRecover is built for 1:1 appointments. Group classes aren’t supported yet.'], ['Can I have several trainers?', 'Yes. Add each trainer and the sessions they offer.'], ['Can clients reschedule themselves?', 'Yes. They see only free times and can pick a trainer.']],
  },
  {
    slug: 'dog-groomers', name: 'Dog groomers', short: 'Pet groomers & trainers',
    title: 'Dog Grooming No-Show Software & Waitlist | SlotRecover',
    h1: 'Keep your grooming table full',
    desc: 'Automatic confirmations and waitlist refills for dog groomers, mobile groomers and pet trainers.',
    intro: 'Grooming appointments are often booked weeks out and forgotten. SlotRecover confirms each booking before the day and offers cancellations to waitlisted pet owners.',
    leaks: ['Owners forget appointments booked a month ago', 'Big-dog grooms leave long gaps when they cancel', 'Mobile groomers lose travel time on no-shows'],
    helps: ['Confirmation requests the day before', 'Cancelled slots offered to waitlisted owners for the same service', 'Works for salon and mobile groomers'],
    example: 'Example: a $90 full groom cancels in the morning. A waitlisted owner who wanted an earlier date books it.',
    appointments: ['Full groom', 'Bath & tidy', 'Nail trim', 'Puppy intro', 'Training session'],
    faqs: [['Can I set longer times for bigger dogs?', 'Yes. Create separate services with their own length and price.'], ['Does it work for mobile grooming?', 'Yes.'], ['Can owners confirm by WhatsApp?', 'Owners confirm with a link. You can send that link on WhatsApp in one tap.']],
  },
  {
    slug: 'tutors', name: 'Tutors', short: 'Tutors & language teachers',
    title: 'Tutoring Lesson Reminders & Cancellation Refills | SlotRecover',
    h1: 'Stop losing income to missed tutoring lessons',
    desc: 'Automatic lesson confirmations and waitlist refills for private tutors, test-prep coaches and language teachers.',
    intro: 'After-school slots are limited and in demand. SlotRecover confirms lessons in advance and offers cancellations to students waiting for a better time.',
    leaks: ['Students cancel for exams, sports or illness', 'Popular after-school slots go unused', 'Parents miss reminders sent by text'],
    helps: ['Confirmation requests to parents or students before each lesson', 'Freed after-school slots offered to your waitlist', 'Clear rescheduling with only free times shown'],
    example: 'Example: a $60 SAT prep lesson at 4 PM is cancelled. A student on the waitlist for weekday afternoons takes it.',
    appointments: ['1:1 lesson', 'Test prep (SAT, ACT, GCSE, A-Level)', 'Language lesson', 'Assessment'],
    faqs: [['Can parents confirm lessons?', 'Yes. Put the parent’s email and phone on the booking.'], ['Do you support online lessons?', 'Yes. Add your meeting details to your note to clients.'], ['Can I run a small tutoring agency?', 'Yes. Add tutors as staff with the subjects they teach.']],
  },
  {
    slug: 'music-teachers', name: 'Music teachers', short: 'Music teachers & academies',
    title: 'Music Lesson Scheduling, Reminders & Waitlist | SlotRecover',
    h1: 'Fill cancelled music lessons without the back-and-forth',
    desc: 'Lesson confirmations and waitlist refills for piano, guitar and vocal teachers and small music academies.',
    intro: 'Missed lessons are lost income for private teachers. SlotRecover confirms lessons ahead of time and offers freed slots to students who want to switch or add a lesson.',
    leaks: ['Students cancel last-minute for school events', 'Prime after-school times are scarce', 'Rescheduling by message takes several back-and-forths'],
    helps: ['Confirmation requests before each lesson', 'Waitlist offers for freed after-school slots', 'Students reschedule to real free times in one step'],
    example: 'Example: a $45 piano lesson is cancelled the morning of. A waitlisted student takes the slot.',
    appointments: ['Piano lesson', 'Guitar lesson', 'Voice lesson', 'Drum lesson', 'Trial lesson'],
    faqs: [['Can I have 30 and 60-minute lessons?', 'Yes. Create a service for each length.'], ['Can several teachers share one account?', 'Yes. Add teachers as staff with the instruments they teach.'], ['Is there a free trial?', `Yes, ${TRIAL_DAYS} days.`]],
  },
  {
    slug: 'photographers', name: 'Photographers', short: 'Portrait & headshot studios',
    title: 'Photography Studio Booking Confirmations | SlotRecover',
    h1: 'Refill cancelled shoots at your photo studio',
    desc: 'Confirm portrait, headshot and studio sessions automatically and offer cancellations to your waitlist.',
    intro: 'Studio time is your inventory. SlotRecover confirms sessions ahead of time and fills cancellations from people waiting for an earlier date.',
    leaks: ['Clients reschedule close to the date', 'Mini-session days have gaps after cancellations', 'Headshot clients book and forget'],
    helps: ['Confirmation requests before each session', 'Automatic waitlist offers for freed studio time', 'Your prep instructions included in reminders'],
    example: 'Example: a $200 headshot session cancels two days before. A waitlisted client who wanted an earlier date takes it.',
    appointments: ['Headshot session', 'Portrait session', 'Mini session', 'Consultation'],
    faqs: [['Can I include what to bring or wear?', 'Yes. Add it as your note to clients.'], ['Do clients need an account?', 'No.'], ['Does it work on my phone?', 'Yes. Install it from your browser.']],
  },
  {
    slug: 'driving-instructors', name: 'Driving instructors', short: 'Driving instructors',
    title: 'Driving Lesson Reminders & Cancellation Waitlist | SlotRecover',
    h1: 'Fill cancelled driving lessons automatically',
    desc: 'Automatic lesson confirmations and waitlist refills for driving instructors and small driving schools.',
    intro: 'Learners cancel for exams, work and weather, and a gap mid-day wastes fuel and time. SlotRecover confirms lessons ahead of time and offers freed slots to waiting learners.',
    leaks: ['Learners cancel the same day', 'Mid-day gaps waste your time on the road', 'Test-prep learners want earlier lessons'],
    helps: ['Confirmation requests before each lesson', 'Waitlist offers to learners who want earlier lessons', 'Instructor-aware availability for driving schools'],
    example: 'Example: a 2-hour lesson cancels in the morning. A learner on the waitlist for extra pre-test practice takes it.',
    appointments: ['1-hour lesson', '2-hour lesson', 'Mock test', 'Motorway lesson'],
    faqs: [['Can I add my pickup instructions?', 'Yes, as your note to clients.'], ['Does it work for a driving school with several instructors?', 'Yes. Add each instructor as staff.'], ['Can learners reschedule themselves?', 'Yes, to real free times only.']],
  },
  {
    slug: 'auto-detailing-and-repair', name: 'Auto detailing & repair', short: 'Auto detailing & garages',
    title: 'Auto Detailing & Garage Appointment Reminders | SlotRecover',
    h1: 'Keep your bays busy when customers cancel',
    desc: 'Confirm detailing and service appointments automatically and refill cancelled bay time from your waitlist.',
    intro: 'A cancelled detail or service leaves a bay and a technician idle. SlotRecover confirms bookings in advance and fills cancellations with customers waiting for an earlier slot.',
    leaks: ['Customers forget drop-off times', 'Long details leave big gaps when cancelled', 'Mobile detailers lose travel time'],
    helps: ['Confirmation requests before each appointment', 'Cancelled bay time offered to waitlisted customers', 'Technician-aware availability'],
    example: 'Example: a $250 full detail cancels the day before. A waitlisted customer who wanted that week takes it.',
    appointments: ['Full detail', 'Ceramic coating consultation', 'Oil change', 'Tire change', 'Inspection'],
    faqs: [['Can I block several hours for one job?', 'Yes. Set the service length.'], ['Does it work for mobile detailing?', 'Yes.'], ['Can I add drop-off instructions?', 'Yes, as your note to clients.']],
  },
  {
    slug: 'home-services', name: 'Home services', short: 'Cleaners & home services',
    title: 'Home Service Appointment Confirmations & Waitlist | SlotRecover',
    h1: 'Fewer wasted trips for cleaners and home service pros',
    desc: 'Automatic visit confirmations and waitlist refills for cleaning companies, handymen and home service businesses.',
    intro: 'A no-one-home visit costs you travel and labor. SlotRecover confirms visits in advance and offers cancelled slots to customers waiting for an earlier date.',
    leaks: ['Customers forget or aren’t home', 'Last-minute cancellations leave crews idle', 'Rescheduling by phone takes time'],
    helps: ['Confirmation requests before each visit', 'Waitlist offers for cancelled visit slots', 'Team-aware availability for crews'],
    example: 'Example: a $160 deep clean cancels the evening before. A waitlisted customer takes the slot the next morning.',
    appointments: ['Deep clean', 'Regular clean', 'Carpet cleaning', 'Handyman visit', 'Quote visit'],
    faqs: [['Can I add access instructions?', 'Yes. Add them as your note to clients.'], ['Can I assign jobs to specific team members?', 'Yes. Add team members as staff with the services they do.'], ['Is there a free trial?', `Yes, ${TRIAL_DAYS} days.`]],
  },
  {
    slug: 'consultants-and-accountants', name: 'Consultants & accountants', short: 'Accountants & consultants',
    title: 'Meeting Reminders for Accountants & Consultants | SlotRecover',
    h1: 'Protect your billable hours from no-shows',
    desc: 'Automatic meeting confirmations and waitlist refills for accountants, tax preparers, financial advisers and consultants.',
    intro: 'In busy seasons, every consultation slot matters. SlotRecover confirms client meetings ahead of time and offers cancellations to clients waiting for a sooner appointment.',
    leaks: ['Clients miss consultations during busy seasons', 'Last-minute cancellations waste prepared time', 'Rescheduling by email drags on'],
    helps: ['Confirmation requests before each meeting', 'Freed consultation slots offered to your waitlist', 'Clients reschedule to real free times'],
    example: 'Example: a $150 tax review cancels the morning of. A client waiting for a sooner slot takes it.',
    appointments: ['Initial consultation', 'Tax review', 'Annual review', 'Document review'],
    faqs: [['Can I share video meeting links?', 'Yes. Add them to your note to clients.'], ['Can colleagues share one account?', 'Yes. Add them as staff.'], ['Is my clients’ data kept private?', 'Yes. Each business’s data is isolated and encrypted.']],
  },
  {
    slug: 'tailors-and-bridal', name: 'Tailors & bridal', short: 'Tailors & bridal fittings',
    title: 'Tailor & Bridal Fitting Appointment Reminders | SlotRecover',
    h1: 'Keep fitting appointments on track',
    desc: 'Confirm alteration and bridal fitting appointments automatically and refill cancellations from your waitlist.',
    intro: 'Fittings run to tight timelines before big events. SlotRecover confirms appointments ahead of time and offers freed slots to clients who need an earlier fitting.',
    leaks: ['Clients forget fittings booked weeks ahead', 'Busy wedding seasons leave no room for gaps', 'Rescheduling by phone takes time'],
    helps: ['Confirmation requests before each fitting', 'Waitlist offers to clients who need an earlier date', 'Staff-aware availability for seamstresses'],
    example: 'Example: a bridal fitting cancels two days before. A waitlisted bride who needed an earlier fitting takes the slot.',
    appointments: ['Bridal fitting', 'Alteration fitting', 'Measurement', 'Consultation'],
    faqs: [['Can I add what to bring to a fitting?', 'Yes, as your note to clients.'], ['Can I set longer bridal appointments?', 'Yes. Each service has its own length.'], ['Is there a free trial?', `Yes, ${TRIAL_DAYS} days.`]],
  },
  {
    slug: 'wellness-studios', name: 'Wellness studios', short: 'Float, sauna & recovery studios',
    title: 'Float, Sauna & Recovery Studio Booking Reminders | SlotRecover',
    h1: 'Refill cancelled sessions at your recovery studio',
    desc: 'Automatic confirmations and waitlist refills for float tanks, infrared saunas, cryotherapy and recovery studios.',
    intro: 'Timed sessions on fixed equipment can’t be made up later. SlotRecover confirms bookings in advance and offers cancelled sessions to people waiting for that time.',
    leaks: ['Session slots on equipment are fixed and perishable', 'Members cancel on busy days', 'Peak evening slots go unused after cancellations'],
    helps: ['Confirmation requests before each session', 'Waitlist offers for freed peak-time sessions', 'Recovered revenue shown on your dashboard'],
    example: 'Example: a $75 float session at 7 PM cancels at 2 PM. A waitlisted client takes it from the offer email.',
    appointments: ['Float session', 'Infrared sauna', 'Cryotherapy', 'Compression session', 'Recovery package'],
    faqs: [['Can I treat each room or device as a resource?', 'Yes. Add each room or device as a “staff” member and tick the sessions it supports.'], ['Can clients join a waitlist?', 'Yes, when rescheduling.'], ['Is there a free trial?', `Yes, ${TRIAL_DAYS} days.`]],
  },
]
